name: Publish .Net MAUI App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install workloads
      run: dotnet workload install maui
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build src\MediaPauser\MediaPauser.csproj -c Release -f net8.0-android --no-restore
